// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOk16LgIdzrnI8xkJATu0md49xkSzlEuM',
    appId: '1:811658618930:web:182f1d3904053018aab42b',
    messagingSenderId: '811658618930',
    projectId: 'foodbuddy-b5548',
    authDomain: 'foodbuddy-b5548.firebaseapp.com',
    storageBucket: 'foodbuddy-b5548.firebasestorage.app',
    measurementId: 'G-5X9JH805LB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKBSgZKBlHI-0bIrOvTbgif02eZa0tAKY',
    appId: '1:811658618930:ios:6c802b7769a9dc7daab42b',
    messagingSenderId: '811658618930',
    projectId: 'foodbuddy-b5548',
    storageBucket: 'foodbuddy-b5548.firebasestorage.app',
    iosBundleId: 'com.example.foodBuddyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOk16LgIdzrnI8xkJATu0md49xkSzlEuM',
    appId: '1:811658618930:web:a6b02379f64660f0aab42b',
    messagingSenderId: '811658618930',
    projectId: 'foodbuddy-b5548',
    authDomain: 'foodbuddy-b5548.firebaseapp.com',
    storageBucket: 'foodbuddy-b5548.firebasestorage.app',
    measurementId: 'G-ZC7H7H7NVD',
  );
}
